namespace: "dataset-api"
replicaCount: 1
image:
  registry: "sadasiva111"
  repository: "api-app"
  image_tag: 1.1
  imagePullSecrets: ""
cpu_requests: 0.5
cpu_limits: 0.5
memory_requests: 512Mi
memory_limits: 1024Mi
network:
  port: '80'
  targetport: '5000'
SYSTEM_ENV: "dev"
postgres_service:
  POSTGRES_HOST: postgresql.postgres
  POSTGRES_PORT: '5432'
  POSTGRES_DATABASE: "postgres"
  POSTGRES_USERNAME: "postgres"
  POSTGRES_PASSWORD: "yj3OyEEppH"

service:
  type: LoadBalancer